import Logo from "../../components/logo/logo";
import "./../layout.css";

export const metadata = {
  title: 'PLING',
  description: 'Generated by Love~',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <div>
            <Logo />
            {children}
        </div>
  )
}
