import Button from "@/components/button/button";
import Logo from "../../components/logo/logo";
import "./../layout.css";
import InfoSvg from "@/imgs/infoSvg";
import ProgSvg from "@/imgs/progSvg";
import LinkSvg from "@/imgs/linkSvg";

export const metadata = {
  title: 'PLING',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Logo />
      <Button id="about-button" uri="/about" icon={<InfoSvg />}/>
      <Button id="link-button" uri="/links" icon={<LinkSvg />}/>
      <Button id="lang-button" uri="/lang" icon={<ProgSvg />}/>

        {children}
    </>
  )
}
