import Button from "@/components/button/button";
import Logo from "../components/logo/logo";
import "./layout.css";
import InfoSvg from "@/imgs/infoSvg";
import ProgSvg from "@/imgs/progSvg";
import LinkSvg from "@/imgs/linkSvg";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

      <Logo />
      <Button uri="/about" icon={<InfoSvg />}/>
      <Button uri="/links" icon={<LinkSvg />}/>
      <Button uri="/lang" icon={<ProgSvg />}/>

        {children}
        </body>
    </html>
  )
}
