import Button from "@/components/button/button";
import Logo from "../components/logo/logo";
import InfoSvg from "@/imgs/infoSvg";
import ProgSvg from "@/imgs/progSvg";
import LinkSvg from "@/imgs/linkSvg";

export const metadata = {
  title: 'PLING',
  description: 'Generated by Love~',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        </body>
    </html>
  )
}
